//Problem Statement: We are given a rod of size ‘N’. It can be cut into pieces. Each length of a piece has a particular price given by the price array. Our task is to find the maximum revenue that can be generated by selling the rod after cutting( if required) into pieces.

//Problem Link: https://www.codingninjas.com/studio/problems/rod-cutting-problem_800284?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf

public class rodCuttingProblem {
    public static int cutRod(int price[], int n) {
        // Write your code here.
        int[] dp = new int[n + 1];

        for (int i = n - 1; i >= 1; i--) {
            for (int j = i; j <= n; j++) {
                dp[j] = Math.max(price[i - 1] + dp[j - i], dp[j]);
            }
        }
        return dp[n];
    }
}